name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Checkout submodules
      run: git submodule update --init --recursive

    - name: Configure VCPKG
      run: ./thirdparty/vcpkg/bootstrap-vcpkg.sh

    - name: Install Dependency libraries
      run: sudo apt-get install libgl-dev tree
      
    - name: Cache Binary VCPKG
      uses: actions/cache@v2.1.0
      with:
        path: |
          $HOME/.cache/vcpkg
          /home/runner/.cache/vcpkg
          ./thirdparty/vcpkg/archives
        key: vcpkg-archive3
      
    - name: Install Dependencies
      run: ./thirdparty/vcpkg/vcpkg --x-manifest-root=. install

    - name: Build project
      run: |
        mkdir build
        cd build
        cmake -DVCPKG_TARGET_TRIPLET=x64-linux ..
        make
        
    - name: Collect artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: |
          ./build/src/wider
          ./build/**/*.so
